In [2]:
import numpy as np

## ndarray 생성 np.array()

In [6]:
list1 = [1,2,3]
array1 = np.array(list1)
type(array1)

numpy.ndarray

## ndarray의 형태와 차원

In [8]:
array1 = np.array([1,2,3]) 
array2 = np.array([[1,2,3],[4,5,6]])
array3 = np.array([[1,2,3]]) #내포되어 있기에 2차원
print(array1.shape)
print(array2.shape)
print(array3.shape)

(3,)
(2, 3)
(1, 3)


In [9]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


## ndarray 데이터 타입

In [10]:
print(array1.dtype)

int32


In [11]:
list2 = [1,2,"test"] # 숫자가 문자열로 바뀜 
array2 = np.array(list2) # ndarray에는 같은 자료형만 있을 수 있음
print(array2.dtype)

<U11


In [12]:
list3 = [1,2,3.0] 
array3 = np.array(list3) #리스트가 ndarray로 바뀌면서 정수가 실수로 바뀜
print(array3.dtype)

float64


## astype()을 통한 타입 변환

In [14]:
array_int = np.array([1,2,3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

array_int1 = array_float.astype("int32")
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


## ndarray에서 axis 기반의 연산함수 수행
- axis 0 : 행 방향, axis 1 : 열 방향

In [17]:
array1 = np.array([[1,2,3],[4,5,6]])
print(array1)
print(array1.sum())
print(array1.sum(axis=0)) # 행 방향(아래방향)
print(array1.sum(axis=1)) # 열 방향(오른쪽방향)

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


### ----------------------------------------------------------------

## ndarray 편리하게 생성하기 - arange, zeros, ones

In [20]:
sequence_array = np.arange(10)
sequence_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
zero_array = np.zeros((4,9))
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
float64 (4, 9)


In [24]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 shape를 변경하는 reshape

In [25]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 변환

In [27]:
# 컬럼 axis 크기를 5에 고정하고 로우 axis 크기를 이에 맞춰 변환하면 2x5으로 변환됨
array2 = array1.reshape(-1,5) 
print(array2, array2.shape)

# 로우 axis 크기를 5에 고정하고 컬럼 axis 크기를 이에 맞춰 변환하면 5x2로 변환됨
array3 = array1.reshape(5,-1)
print(array3, array3.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [28]:
# reshape()는 (-1,1) 또는 (-1,)와 같은 형태로 주로 사용됨

# 1차원 ndarray를 2차원으로 변환
array_2d = array1.reshape(-1,1)
print(array_2d.shape)
print(array_2d)

# 2차원 ndarray를 1차원으로 변환
array_1d = array_2d.reshape(-1,)
print(array_1d.shape)
print(array_1d)

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10,)
[0 1 2 3 4 5 6 7 8 9]


## ndarray의 데이터 세트 선택하기 - 인덱싱
- 특정 위치의 단일값 추출
- 슬라이싱 : 연속적
- 팬시 인덱싱 : 인덱싱 집합을 리스트 또는 ndarray 형태로 지정
- 불린 인덱싱 : 조건에 해당하는지를 기반으로 true만 반환

### 특정 위치의 단일값 추출

In [32]:
array1 = np.arange(1,10)
print(array1)
print(array1[4])
print(array1[-1])

[1 2 3 4 5 6 7 8 9]
5
9


In [33]:
array2d = array1.reshape(3,3)
print(array2d)
print(array2d[0,0])
print(array2d[2,2])
print(array2d[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
5


### 슬라이싱

In [35]:
array2 = array1[:3]
print(array2)
array3 = array1[3:]
print(array3)
array4 = array1[4:7]
print(array4)

[1 2 3]
[4 5 6 7 8 9]
[5 6 7]


### 팬시 인덱싱

In [42]:
array1d = np.arange(1,10);
array2d = array1d.reshape(3,3);
print(array2d)

array3 = array2d[[0,2],0:2]
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [7 8]]


### 불린 인덱싱

In [43]:
var=array1d>5
print(var)
print(type(var))

[False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [44]:
print(array1d[var])

[6 7 8 9]


## 행열의 정렬 (오름차순)
- np.sort() : 원형 유지, 정렬된 행렬 반환
- ndarray.sort() : 원형을 정렬된 행렬로 변환, 변환값 없음   
- argsort() : 원본 행렬 정렬 시 정렬된 행렬의 원본 행렬 인덱스 반환
* 내림차순은 오름차순에 [::-1] 붙이면 된다.

In [50]:
org_array = np.array([3,1,9,5])
sort1 = np.sort(org_array)
print(sort1)
print(org_array) #원본 행렬 정렬안됨

sort2 = org_array.sort() #반환값 없음
print(sort2)
print(org_array) #원본 행렬 정렬됨

[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [51]:
sort1_d = np.sort(org_array)[::-1]
print(sort1_d)

[9 5 3 1]


In [4]:
array2d = np.array([[8,12],
                   [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0) #행방향 정렬
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [6]:
name_array = np.array(["John",'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78,95,84,98,88])
# name_array와 score_array가 딕셔너리처럼 인덱스로 연결되어 있을 떄
# argsort 사용하면 편하다.
sort_indices = np.argsort(score_array)
print(sort_indices)

score_array_sort = score_array[sort_indices]
name_array_sort = name_array[sort_indices]
print(score_array_sort)
print(name_array_sort)

[0 2 4 1 3]
[78 84 88 95 98]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치행렬 구하기

- 행렬 내적 : np.dot()

In [8]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print("행렬 내적 결과: \n", dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


- 전치 행렬 : np.transpose()

In [9]:
A = np.array([[1,2,3],
             [4,5,6]])
transpose_A = np.transpose(A)
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]
